on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./open-source-election-game/package-lock.json"
    - name: Install dependencies
      working-directory: ./open-source-election-game
      run: npm install
    - name: Build
      working-directory: ./open-source-election-game
      run: npm run build --if-present
    - name: Run tests
      working-directory: ./open-source-election-game
      run: npm test
    - name: Deploy
      working-directory: ./open-source-election-game
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}